//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/inputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""inputActions"",
    ""maps"": [
        {
            ""name"": ""hero"",
            ""id"": ""31152233-42ed-4486-865e-f6127c134d98"",
            ""actions"": [
                {
                    ""name"": ""MoveBack"",
                    ""type"": ""Button"",
                    ""id"": ""9c9f7fd2-1293-413a-99eb-f1fac34a1238"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveForward"",
                    ""type"": ""Button"",
                    ""id"": ""01895b9a-a6bc-4e3a-b405-fb0352bbc016"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""06b14636-bd3d-4671-a55d-fcfbf1358249"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SeatDown"",
                    ""type"": ""Button"",
                    ""id"": ""d58ac9e8-a16f-4873-9ca7-b35175570af8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""79adb83d-83d2-4d09-a112-a260d4006c4d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SuperAttack1"",
                    ""type"": ""Button"",
                    ""id"": ""4d34dda4-ea1a-47c7-9029-a8f43678adb4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SuperAttack2"",
                    ""type"": ""Button"",
                    ""id"": ""175bbb8d-71cc-4e84-b8b3-44624412520c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""e39c90dc-cc25-4325-b43e-ebb6a818e729"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d40d75ec-d14f-48e0-8fd3-9db857c22a61"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb4ff3f1-15cf-4ecd-9669-c697d2206f26"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71e619a9-9fa6-41de-abea-af28faf4c2e0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3b392e4-8cf5-4fa3-83e2-2682281a7a19"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SeatDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""926d1655-aaf3-4de0-825f-0a97c9d9a0a1"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b60c87f-aa68-408b-8db8-d8234d88283b"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SuperAttack1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b08d37b1-a018-4408-84b6-49a627c89aa9"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SuperAttack2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bec85aeb-b556-4c72-9247-2667bb4b3eea"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""enemy"",
            ""id"": ""12b9a241-ac71-4a50-a579-0cc22ae9067c"",
            ""actions"": [
                {
                    ""name"": ""MoveBack"",
                    ""type"": ""Button"",
                    ""id"": ""5eafece7-c5b3-4e80-83d6-3dda7bdcee81"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveForward"",
                    ""type"": ""Button"",
                    ""id"": ""2578931a-55ad-4c1f-ab6d-77ba8a59f284"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""e6e857be-bd35-4682-97bd-6dc9208bf67f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SeatDown"",
                    ""type"": ""Button"",
                    ""id"": ""c769f3d9-75f8-427b-938e-2a23c1abd38d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""fc4449e2-5e2b-484f-a6c7-5142517cbd86"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SuperAttack1"",
                    ""type"": ""Button"",
                    ""id"": ""adf68e37-8e8b-49bd-9aa0-5fbe61df3110"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SuperAttack2"",
                    ""type"": ""Button"",
                    ""id"": ""f13b2a48-c2a8-479a-872e-2f7597452e29"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""628438f1-9315-40ec-98af-a8ba92988f61"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b2eb561d-0e9a-4163-88df-e81d190d6a0e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8c14992-2557-43db-be11-f3bcac61a0c2"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3239aa51-fb5e-4904-82da-29a457235131"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab182455-3f4f-4100-a7e9-a14c9604eba5"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SeatDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc7cd0f2-52c7-4aeb-b5a1-e9fdb052c769"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52cf8243-7c43-411f-bc9f-9eb49ecdf48c"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SuperAttack1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f8a8933-fde1-4a9b-8cc8-b4daba0c68d7"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SuperAttack2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a99dc59e-4af5-438b-8f6a-2eebf210b0b3"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // hero
        m_hero = asset.FindActionMap("hero", throwIfNotFound: true);
        m_hero_MoveBack = m_hero.FindAction("MoveBack", throwIfNotFound: true);
        m_hero_MoveForward = m_hero.FindAction("MoveForward", throwIfNotFound: true);
        m_hero_Jump = m_hero.FindAction("Jump", throwIfNotFound: true);
        m_hero_SeatDown = m_hero.FindAction("SeatDown", throwIfNotFound: true);
        m_hero_Attack = m_hero.FindAction("Attack", throwIfNotFound: true);
        m_hero_SuperAttack1 = m_hero.FindAction("SuperAttack1", throwIfNotFound: true);
        m_hero_SuperAttack2 = m_hero.FindAction("SuperAttack2", throwIfNotFound: true);
        m_hero_Block = m_hero.FindAction("Block", throwIfNotFound: true);
        // enemy
        m_enemy = asset.FindActionMap("enemy", throwIfNotFound: true);
        m_enemy_MoveBack = m_enemy.FindAction("MoveBack", throwIfNotFound: true);
        m_enemy_MoveForward = m_enemy.FindAction("MoveForward", throwIfNotFound: true);
        m_enemy_Jump = m_enemy.FindAction("Jump", throwIfNotFound: true);
        m_enemy_SeatDown = m_enemy.FindAction("SeatDown", throwIfNotFound: true);
        m_enemy_Attack = m_enemy.FindAction("Attack", throwIfNotFound: true);
        m_enemy_SuperAttack1 = m_enemy.FindAction("SuperAttack1", throwIfNotFound: true);
        m_enemy_SuperAttack2 = m_enemy.FindAction("SuperAttack2", throwIfNotFound: true);
        m_enemy_Block = m_enemy.FindAction("Block", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // hero
    private readonly InputActionMap m_hero;
    private List<IHeroActions> m_HeroActionsCallbackInterfaces = new List<IHeroActions>();
    private readonly InputAction m_hero_MoveBack;
    private readonly InputAction m_hero_MoveForward;
    private readonly InputAction m_hero_Jump;
    private readonly InputAction m_hero_SeatDown;
    private readonly InputAction m_hero_Attack;
    private readonly InputAction m_hero_SuperAttack1;
    private readonly InputAction m_hero_SuperAttack2;
    private readonly InputAction m_hero_Block;
    public struct HeroActions
    {
        private @InputActions m_Wrapper;
        public HeroActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveBack => m_Wrapper.m_hero_MoveBack;
        public InputAction @MoveForward => m_Wrapper.m_hero_MoveForward;
        public InputAction @Jump => m_Wrapper.m_hero_Jump;
        public InputAction @SeatDown => m_Wrapper.m_hero_SeatDown;
        public InputAction @Attack => m_Wrapper.m_hero_Attack;
        public InputAction @SuperAttack1 => m_Wrapper.m_hero_SuperAttack1;
        public InputAction @SuperAttack2 => m_Wrapper.m_hero_SuperAttack2;
        public InputAction @Block => m_Wrapper.m_hero_Block;
        public InputActionMap Get() { return m_Wrapper.m_hero; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HeroActions set) { return set.Get(); }
        public void AddCallbacks(IHeroActions instance)
        {
            if (instance == null || m_Wrapper.m_HeroActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HeroActionsCallbackInterfaces.Add(instance);
            @MoveBack.started += instance.OnMoveBack;
            @MoveBack.performed += instance.OnMoveBack;
            @MoveBack.canceled += instance.OnMoveBack;
            @MoveForward.started += instance.OnMoveForward;
            @MoveForward.performed += instance.OnMoveForward;
            @MoveForward.canceled += instance.OnMoveForward;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @SeatDown.started += instance.OnSeatDown;
            @SeatDown.performed += instance.OnSeatDown;
            @SeatDown.canceled += instance.OnSeatDown;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @SuperAttack1.started += instance.OnSuperAttack1;
            @SuperAttack1.performed += instance.OnSuperAttack1;
            @SuperAttack1.canceled += instance.OnSuperAttack1;
            @SuperAttack2.started += instance.OnSuperAttack2;
            @SuperAttack2.performed += instance.OnSuperAttack2;
            @SuperAttack2.canceled += instance.OnSuperAttack2;
            @Block.started += instance.OnBlock;
            @Block.performed += instance.OnBlock;
            @Block.canceled += instance.OnBlock;
        }

        private void UnregisterCallbacks(IHeroActions instance)
        {
            @MoveBack.started -= instance.OnMoveBack;
            @MoveBack.performed -= instance.OnMoveBack;
            @MoveBack.canceled -= instance.OnMoveBack;
            @MoveForward.started -= instance.OnMoveForward;
            @MoveForward.performed -= instance.OnMoveForward;
            @MoveForward.canceled -= instance.OnMoveForward;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @SeatDown.started -= instance.OnSeatDown;
            @SeatDown.performed -= instance.OnSeatDown;
            @SeatDown.canceled -= instance.OnSeatDown;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @SuperAttack1.started -= instance.OnSuperAttack1;
            @SuperAttack1.performed -= instance.OnSuperAttack1;
            @SuperAttack1.canceled -= instance.OnSuperAttack1;
            @SuperAttack2.started -= instance.OnSuperAttack2;
            @SuperAttack2.performed -= instance.OnSuperAttack2;
            @SuperAttack2.canceled -= instance.OnSuperAttack2;
            @Block.started -= instance.OnBlock;
            @Block.performed -= instance.OnBlock;
            @Block.canceled -= instance.OnBlock;
        }

        public void RemoveCallbacks(IHeroActions instance)
        {
            if (m_Wrapper.m_HeroActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IHeroActions instance)
        {
            foreach (var item in m_Wrapper.m_HeroActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HeroActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public HeroActions @hero => new HeroActions(this);

    // enemy
    private readonly InputActionMap m_enemy;
    private List<IEnemyActions> m_EnemyActionsCallbackInterfaces = new List<IEnemyActions>();
    private readonly InputAction m_enemy_MoveBack;
    private readonly InputAction m_enemy_MoveForward;
    private readonly InputAction m_enemy_Jump;
    private readonly InputAction m_enemy_SeatDown;
    private readonly InputAction m_enemy_Attack;
    private readonly InputAction m_enemy_SuperAttack1;
    private readonly InputAction m_enemy_SuperAttack2;
    private readonly InputAction m_enemy_Block;
    public struct EnemyActions
    {
        private @InputActions m_Wrapper;
        public EnemyActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveBack => m_Wrapper.m_enemy_MoveBack;
        public InputAction @MoveForward => m_Wrapper.m_enemy_MoveForward;
        public InputAction @Jump => m_Wrapper.m_enemy_Jump;
        public InputAction @SeatDown => m_Wrapper.m_enemy_SeatDown;
        public InputAction @Attack => m_Wrapper.m_enemy_Attack;
        public InputAction @SuperAttack1 => m_Wrapper.m_enemy_SuperAttack1;
        public InputAction @SuperAttack2 => m_Wrapper.m_enemy_SuperAttack2;
        public InputAction @Block => m_Wrapper.m_enemy_Block;
        public InputActionMap Get() { return m_Wrapper.m_enemy; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EnemyActions set) { return set.Get(); }
        public void AddCallbacks(IEnemyActions instance)
        {
            if (instance == null || m_Wrapper.m_EnemyActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_EnemyActionsCallbackInterfaces.Add(instance);
            @MoveBack.started += instance.OnMoveBack;
            @MoveBack.performed += instance.OnMoveBack;
            @MoveBack.canceled += instance.OnMoveBack;
            @MoveForward.started += instance.OnMoveForward;
            @MoveForward.performed += instance.OnMoveForward;
            @MoveForward.canceled += instance.OnMoveForward;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @SeatDown.started += instance.OnSeatDown;
            @SeatDown.performed += instance.OnSeatDown;
            @SeatDown.canceled += instance.OnSeatDown;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @SuperAttack1.started += instance.OnSuperAttack1;
            @SuperAttack1.performed += instance.OnSuperAttack1;
            @SuperAttack1.canceled += instance.OnSuperAttack1;
            @SuperAttack2.started += instance.OnSuperAttack2;
            @SuperAttack2.performed += instance.OnSuperAttack2;
            @SuperAttack2.canceled += instance.OnSuperAttack2;
            @Block.started += instance.OnBlock;
            @Block.performed += instance.OnBlock;
            @Block.canceled += instance.OnBlock;
        }

        private void UnregisterCallbacks(IEnemyActions instance)
        {
            @MoveBack.started -= instance.OnMoveBack;
            @MoveBack.performed -= instance.OnMoveBack;
            @MoveBack.canceled -= instance.OnMoveBack;
            @MoveForward.started -= instance.OnMoveForward;
            @MoveForward.performed -= instance.OnMoveForward;
            @MoveForward.canceled -= instance.OnMoveForward;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @SeatDown.started -= instance.OnSeatDown;
            @SeatDown.performed -= instance.OnSeatDown;
            @SeatDown.canceled -= instance.OnSeatDown;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @SuperAttack1.started -= instance.OnSuperAttack1;
            @SuperAttack1.performed -= instance.OnSuperAttack1;
            @SuperAttack1.canceled -= instance.OnSuperAttack1;
            @SuperAttack2.started -= instance.OnSuperAttack2;
            @SuperAttack2.performed -= instance.OnSuperAttack2;
            @SuperAttack2.canceled -= instance.OnSuperAttack2;
            @Block.started -= instance.OnBlock;
            @Block.performed -= instance.OnBlock;
            @Block.canceled -= instance.OnBlock;
        }

        public void RemoveCallbacks(IEnemyActions instance)
        {
            if (m_Wrapper.m_EnemyActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IEnemyActions instance)
        {
            foreach (var item in m_Wrapper.m_EnemyActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_EnemyActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public EnemyActions @enemy => new EnemyActions(this);
    public interface IHeroActions
    {
        void OnMoveBack(InputAction.CallbackContext context);
        void OnMoveForward(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSeatDown(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnSuperAttack1(InputAction.CallbackContext context);
        void OnSuperAttack2(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
    }
    public interface IEnemyActions
    {
        void OnMoveBack(InputAction.CallbackContext context);
        void OnMoveForward(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSeatDown(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnSuperAttack1(InputAction.CallbackContext context);
        void OnSuperAttack2(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
    }
}
